# Tutorial Makefile
#
# Copyright (C) 2001-2008 NLTK Project
# Author: Steven Bird <sb@csse.unimelb.edu.au>
#         Edward Loper <edloper@gradient.cis.upenn.edu>
# URL: <http://nltk.org>
# For license information, see LICENSE.TXT

PAPER_SIZE = a4

CHAPTERS = ch00.rst ch01.rst ch02.rst ch03.rst ch04.rst ch05.rst ch06.rst\
           ch07.rst ch08.rst ch09.rst ch10.rst ch11.rst ch12.rst ch13.rst ch14.rst\
           app-regexps.rst app-unicode.rst app-nlp-python.rst app-modules.rst\
           app-cheat-sheet.rst app-projects.rst term_index.rst

REF_EXTENSION = .ref

PDF := $(CHAPTERS:.rst=.pdf)
HTML := $(CHAPTERS:.rst=.html)
XML := $(CHAPTERS:.rst=.xml)
ERRS := $(CHAPTERS:.rst=.errs)
REF := $(CHAPTERS:.rst=$(REF_EXTENSION))
PY := $(CHAPTERS:.rst=.py)
TEX := $(CHAPTERS:.rst=.tex)

BIBTEX_FILE = ../refs.bib

PYTHON = python
PDFLATEX = TEXINPUTS=".:..:ucs:" pdflatex -halt-on-error
EXAMPLES = ../examples.py
RST = ../rst.py
RST2REF = $(RST) --ref
RST2HTML = $(RST) --html
RST2DOCBOOK = $(RST) --docbook
RST2LATEX = $(RST) --latex --$(PAPER_SIZE)
DOCTEST = PYTHONPATH=../.. $(PYTHON) ../../nltk/test/doctest_driver.py
BIBTEX = bibtex -terse
#get from environment
#DOCBOOKDTD = /sw/share/xml/dtd/docbookx/4.4.0/docbookx.dtd
#DOCBOOKDTD = /opt/local/share/xml/docbook/4.4/docbookx.dtd

# <http://www.spinellis.gr/sw/textproc/bib2xhtml/>
BIB2XHTML = bib2xhtml -s named

WEB = $(USER)@shell.sourceforge.net:/home/groups/n/nl/nltk/htdocs
BETA = $(WEB)/beta
RSYNC_OPTS = -arvz -e ssh --relative --cvs-exclude

LATEX_STYLESHEET_PATH = ../definitions.sty

.SUFFIXES: .rst .html .pdf .errs .py

help: usage
usage:
	@echo "Usage:"
	@echo "    make all         -- Build HTML & PDF output"
	@echo "    make html        -- Build HTML output"
	@echo "    make pdf         -- Build PDF output"
	@echo "    make xml         -- Build XML output"
	@echo "    make errs        -- Run doctest to generate .errs files"
	@echo "    make clean       -- Remove all built files"

all: html pdf examples book clean_up
html: $(HTML) bibliography.html 
pdf: $(PDF)
xml: ch00.xml ch01.xml ch02.xml ch03.xml ch04.xml ch05.xml ch06.xml ch07.xml ch08.xml ch09.xml\
     app-regexps.xml app-unicode.xml app-nlp-python.xml app-modules.xml app-cheat-sheet.xml
book: book.html book.bbl book.pdf
examples: $(PY)
errs: $(ERRS)
	ls -l $(ERRS)

clean:	clean_up
	rm -f $(PDF) $(HTML) $(ERRS) $(REF) $(PY) $(TEX)
	rm -f book.pdf book.html book.tex bibliography.html
	rm -rf tree_images

clean_up:
	rm -f *.log *.aux *.out *.errs *~ *.bbl *.idx *.ilg *.ind *.toc *.blg

.PRECIOUS: $(REF)

%$(REF_EXTENSION): %.rst
	$(RST2REF) $<

%.html: %.rst $(REF) revision.rst
	$(RST2HTML) $(REF) $< 

%.xml: %.rst $(RST) ../docbook.py $(REF) revision.rst
	$(RST2DOCBOOK) $(REF) $<
#	$(PYTHON) ../xmlpp.py $@ > tmp.xml
#	mv tmp.xml $@
	xmllint --noout --dtdvalid $(DOCBOOKDTD) $@

%.tex: %.rst $(REF) revision.rst
	$(RST2LATEX) $(REF) $< 

revision.rst: $(CHAPTERS)
	echo "This document is" > revision.rst
	svn info | grep Revision >> revision.rst
	date >> revision.rst

%.bbl: %.tex $(BIBTEX_FILE)
	rm -f $*.bbl
	@echo "pdflatex $< -> $*.pdf (for bibtex)"
	@(true | $(PDFLATEX) $< >/dev/null) || \
                 (cat $*.log && rm -f $*.pdf && false)
	@echo $(BIBTEX) $*
	@(true | $(BIBTEX) $* || (rm -f $*.pdf $*.bbl && false))

bibliography.html: $(BIBTEX_FILE) bib_template.html
	cp bib_template.html $@
	$(BIB2XHTML) $< $@

book.html: book.rst $(CHAPTERS) part1.rst part2.rst part3.rst
	$(RST2HTML) $<

book.tex: book.rst $(CHAPTERS) part1.rst part2.rst part3.rst
	$(RST2LATEX) --documentclass=book --bibliography $<

# This fairly complex target here will cause pdflatex to only generate
# output if it fails; and to clean up after itself if it fails.  Also,
# it will only run a second pass if it detects that it's necessary (by
# scanning the log file for a warning message).
%.pdf: %.tex
	rm -f $*.ind
	@echo "pdflatex $< -> $*.pdf (first pass)"
	@(true | $(PDFLATEX) $< >/dev/null) || \
                 (cat $*.log && rm -f $*.pdf && false)
	@if [ "`grep -i 'Warning.*Rerun' $*.log`" ]; \
	    then \
	        echo "pdflatex $< -> $*.pdf (second pass)";\
	        (true | $(PDFLATEX) $< >/dev/null) || \
                       (cat $*.log && rm -f $*.pdf && false);\
	    fi
	@(if [ -e $*.idx ]; \
	    then \
	        echo "makeindex $*.idx"; makeindex $*.idx; \
	    fi)
	@echo "pdflatex $< -> $*.pdf (last pass)"
	@(true | $(PDFLATEX) $< >/dev/null) || \
                 (cat $*.log && rm -f $*.pdf && false)
	@echo "cleaning up latex temp files..."
	rm -f $*.log $*.aux $*.out $*.errs $*.bbl 
	rm -f $*.idx $*.ilg $*.ind $*.toc $*.blg

book.pdf: book.bbl book.tex

.rst.errs:
	$(DOCTEST) $< --ellipsis --normalize_whitespace --udiff &> $@

rsync-en:
	rsync $(RSYNC_OPTS) . $(WEB)/doc/en/

rsync-en-beta:
	rsync $(RSYNC_OPTS) . $(BETA)/doc/en/

.rst.py:
	$(PYTHON) $(EXAMPLES) $< > $@
