# Natural Language Toolkit: Tutorial report Makefile
#
# Copyright (C) 2001-2005 University of Pennsylvania
# Author: Edward Loper <edloper@gradient.cis.upenn.edu>
#         Steven Bird <sb@csse.unimelb.edu.au>
# URL: <http://nltk.sf.net>
# For license information, see LICENSE.TXT
#
# $Id$

# The name of the tutorial (without the .xml extension)
REPORT = $(notdir $(shell pwd))

# Include the tutorial makefile.
include ../Makefile.tutorial
